[build]
  publish = "."

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
